### ISSUE TITLE
atom-ide-terminal: Error starting process

### ISSUE THREAD

**Issue by chrisdothtml** [facebook-atom/atom-ide-ui#250]
### Description
Tried to open the terminal for the first time after installing `atom-ide-ui`, getting an error message. Disabling other packages and/or restarting atom doesn't fix it

### Expected Behavior
The terminal should start up

### Actual Behavior
An error is displayed in the terminal pane:

> Error starting process:
> Error: Cannot find module '/Users/chris/.atom/packages/atom-ide-ui/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v57-darwin-x64/pty.node'

### Versions
* Atom: v1.28.0-beta0
* Client OS: macOS High Sierra v10.13.4
* atom-ide-ui: v0.11.2

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── atom-ide-ui@0.11.2
├── busy-signal@1.4.3
├── editorconfig@2.2.2
├── file-icons@2.1.21
├── intentions@1.1.5
```

**Comment by hansonw** [comment]
Just published v0.12.0 that should work with 1.28-beta.
